language: go
sudo: required

go: 
  - 1.9

install:
  - go get -u github.com/golang/dep/cmd/dep && dep ensure

script:
  - go test --cover
  - go build .
  - ./helmdeploy --help
  - ./test/e2e.sh

env:
  - CHANGE_MINIKUBE_NONE_USER=true
